stages:
  - build
  - test
  - deploy
  - test deploy

image: node

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ./node_modules

build website:
  stage: build
  script:
    - npm cache clean --force
    - npm install
    - npm install -g gatsby-cli
    - gatsby clean
    - gatsby build
  artifacts:
    paths:
      - ./public

test artifact:
  image: alpine
  stage: test
  script:
    - grep "Gatsby" ./public/index.html

test website:
  stage: test
  script:
    - npm cache clean --force
    - npm install
    - npm install -g gatsby-cli
    - gatsby clean
    - gatsby build
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./public/index.html
    - gatsby serve&
    - sleep 3
    - curl "http://localhost:9000" | tac | tac | grep "Gatsby"

deploy surge:
  stage: deploy
  script:
    - npm install --global surge
    - surge --project ./public --domain cicdsite.surge.sh

test deployment:
  image: alpine
  stage: test deploy
  script:
    - apk --no-cache add curl
    - curl "cicdsite.surge.sh" | tac | tac | grep "Gatsby"
