stages:
  - build
  - test
  - deploy

image: node

build website:
  stage: build
  script:
    - npm cache clean --force
    - npm install
    - npm install -g gatsby-cli
    - gatsby clean
    - gatsby build
  artifacts:
    paths:
      - ./public

test artifact:
  image: alpine
  stage: test
  script:
    - grep "Gatsby" ./public/index.html

test website:
  stage: test
  script:
    - npm cache clean --force
    - npm install
    - npm install -g gatsby-cli
    - gatsby clean
    - gatsby build
    - gatsby serve&
    - sleep 3
    - curl "http://localhost:9000" | tac | tac | grep "Gatsby"

deploy surge:
  stage: deploy
  script:
    - npm install --global surge
    - surge --project ./public --domain cicdsite.surge.sh

