stages:
  - build
  - test
  - deploy staging
  - test staging
  - deploy production
  - test production

image: node

variables:
  STAGE: "http://cicdsite-stage.surge.sh"
  PROD: "http://cicdsite-prod.surge.sh"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ./node_modules

build website:
  stage: build
  script:
    - npm cache clean --force
    - npm install
    - npm install -g gatsby-cli
    - gatsby clean
    - gatsby build
  artifacts:
    paths:
      - ./public

test artifact:
  image: alpine
  stage: test
  script:
    - grep "Gatsby" ./public/index.html

test website:
  stage: test
  script:
    - npm cache clean --force
    - npm install
    - npm install -g gatsby-cli
    - gatsby clean
    - gatsby build
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./public/index.html
    - gatsby serve&
    - sleep 3
    - curl "http://localhost:9000" | tac | tac | grep "Gatsby"

deploy staging:
  stage: deploy staging
  environment:
    name: staging
    url: $STAGE
  only:
    - master
  script:
    - npm install --global surge
    - surge --project ./public --domain $STAGE

test staging:
  image: alpine
  stage: test staging
  only:
    - master
  script:
    - apk --no-cache add curl
    - curl $STAGE | tac | tac | grep "Gatsby"

deploy production:
  stage: deploy production
  environment:
    name: production
    url: $PROD
  when: manual
  allow_failure: false
  only:
    - master
  script:
    - npm install --global surge
    - surge --project ./public --domain $PROD

test production:
  image: alpine
  stage: test production
  only:
    - master
  script:
    - apk --no-cache add curl
    - curl $PROD | tac | tac | grep "Gatsby"


