stages:
  - build
  - test
  - deploy staging
  - test staging
  - deploy production
  - test production

image: node

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ./node_modules

build website:
  stage: build
  script:
    - npm cache clean --force
    - npm install
    - npm install -g gatsby-cli
    - gatsby clean
    - gatsby build
  artifacts:
    paths:
      - ./public

test artifact:
  image: alpine
  stage: test
  script:
    - grep "Gatsby" ./public/index.html

test website:
  stage: test
  script:
    - npm cache clean --force
    - npm install
    - npm install -g gatsby-cli
    - gatsby clean
    - gatsby build
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./public/index.html
    - gatsby serve&
    - sleep 3
    - curl "http://localhost:9000" | tac | tac | grep "Gatsby"

deploy surge stage:
  stage: deploy staging
  environment:
    name: staging
    url: cicdsite-stage.surge.sh
  script:
    - npm install --global surge
    - surge --project ./public --domain cicdsite-stage.surge.sh

test staging:
  image: alpine
  stage: test deploy
  script:
    - apk --no-cache add curl
    - curl "cicdsite-stage.surge.sh" | tac | tac | grep "Gatsby"

deploy surge prod:
  stage: deploy production
  environment:
    name: production
    url: cicdsite-prod.surge.sh
  script:
    - npm install --global surge
    - surge --project ./public --domain cicdsite-prod.surge.sh

test production:
  image: alpine
  stage: test deploy
  script:
    - apk --no-cache add curl
    - curl "cicdsite-prod.surge.sh" | tac | tac | grep "Gatsby"
